# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

# Install Node.js and build dependencies for native modules
RUN pkg update && \
    pkg install -y \
    FreeBSD-clang \
    FreeBSD-clibs-dev \
    binutils \
    coreutils \
    node24 \
    npm-node24 \
    python311 \
    gmake \
    git \
    sqlite3 \
    postgresql17-client \
    ca_root_nss && \
    ln -sf /usr/local/bin/python3.11 /usr/local/bin/python && \
    ln -sf /usr/local/bin/python3.11 /usr/local/bin/python3

# Install n8n globally and capture version
ENV npm_config_python=/usr/local/bin/python3.11
RUN npm install -g n8n && \
    mkdir -p /app && npm list -g n8n --depth=0 | grep n8n | sed 's/.*@//' > /app/version

# Production image
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="node24 sqlite3 postgresql17-client git ca_root_nss"
ARG UPSTREAM_URL="https://registry.npmjs.org/n8n/latest"
ARG UPSTREAM_JQ=".version"
ARG HEALTHCHECK_ENDPOINT="http://localhost:5678/healthz"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="n8n" \
      org.opencontainers.image.description="Workflow automation tool on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/n8n" \
      org.opencontainers.image.url="https://n8n.io/" \
      org.opencontainers.image.documentation="https://docs.n8n.io/" \
      org.opencontainers.image.licenses="Sustainable-Use-1.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="5678" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}" \
      io.daemonless.wip="true"

# Install runtime dependencies
RUN pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy n8n from builder and fix permissions for non-root execution
COPY --from=builder /app/version /app/version
COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY patch_sqlite.sh /tmp/patch_sqlite.sh

RUN chmod -R o+rX /usr/local/lib/node_modules/n8n && \
    ln -sf /usr/local/lib/node_modules/n8n/bin/n8n /usr/local/bin/n8n && \
    sh /tmp/patch_sqlite.sh && rm /tmp/patch_sqlite.sh

# Create config directory
RUN mkdir -p /config && \
    chown -R bsd:bsd /config

# Copy service definitions and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# Environment
ENV N8N_USER_FOLDER=/config \
    N8N_PORT=5678 \
    N8N_PROTOCOL=http \
    NODE_ENV=production

# --- Expose (Injected by Generator) ---
EXPOSE 5678

# --- Volumes (Injected by Generator) ---
VOLUME /config