# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
ARG NODE_VERSION=22
ARG PYTHON_VERSION=313
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder
ARG NODE_VERSION
ARG PYTHON_VERSION

# Install Node.js and build dependencies for native modules
RUN pkg update && \
    pkg install -y \
    FreeBSD-clang \
    FreeBSD-clibs-dev \
    FreeBSD-libexecinfo-dev \
    FreeBSD-openssl-dev \
    FreeBSD-runtime-dev \
    FreeBSD-toolchain \
    FreeBSD-utilities-dev \
    FreeBSD-zlib-dev \
    cmake \
    node${NODE_VERSION} \
    npm-node${NODE_VERSION} \
    python${PYTHON_VERSION} \
    gmake \
    git \
    rust \
    ca_root_nss && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/* && \
    ln -sf /usr/local/bin/python3.13 /usr/local/bin/python3 && \
    ln -sf /usr/local/bin/python3.13 /usr/local/bin/python

# --os linux installs linux variant of libsql (JS/WASM only, no native binary); n8n uses sqlite3
# Install n8n (--force bypasses libsql platform check; native binary built below)
RUN npm install -g n8n --force && \
    npm cache clean --force && \
    mkdir -p /app && npm list -g n8n --depth=0 | grep n8n | sed 's/.*@//' > /app/version


# Build libsql native binding for FreeBSD and place in n8n's nested node_modules
RUN git clone --no-checkout https://github.com/tursodatabase/libsql-js /tmp/libsql-js && \
    cd /tmp/libsql-js && \
    git checkout 55bee86d1c284f1ddf2b9e280e870d2b6cef884a && \
    cargo build --release 2>&1 | tail -5 && \
    find /usr/local/lib/node_modules -path "*/libsql/libsql.linux-x64*" | \
      xargs -I{} sh -c 'cp target/release/liblibsql_js.so "$(dirname {})/libsql.freebsd-x64.node"' && \
    rm -rf /tmp/libsql-js ~/.cargo/registry ~/.cargo/git

# Set up Python task runner at the path n8n expects
RUN mkdir -p /usr/local/lib/node_modules/@n8n && \
    cd /usr/local/lib/node_modules/@n8n && \
    git clone --depth 1 https://github.com/n8n-io/n8n.git n8n-src && \
    mv n8n-src/packages/@n8n/task-runner-python . && \
    rm -rf n8n-src && \
    cd task-runner-python && \
    python3 -m venv .venv && \
    .venv/bin/python -m ensurepip --upgrade && \
    .venv/bin/pip install --no-cache-dir "websockets>=15.0.1"

# Production image
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG NODE_VERSION
ARG PYTHON_VERSION
ARG PACKAGES="node${NODE_VERSION} sqlite3 git ca_root_nss GraphicsMagick icu python${PYTHON_VERSION}"
ARG UPSTREAM_URL="https://registry.npmjs.org/n8n/latest"
ARG UPSTREAM_JQ=".version"
ARG HEALTHCHECK_ENDPOINT="http://localhost:5678/healthz"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="n8n" \
      org.opencontainers.image.description="Fair-code workflow automation platform with native AI capabilities — combine visual building with custom code and 400+ integrations." \
      org.opencontainers.image.source="https://github.com/daemonless/n8n" \
      org.opencontainers.image.url="https://n8n.io/" \
      org.opencontainers.image.documentation="https://docs.n8n.io/" \
      org.opencontainers.image.licenses="Sustainable-Use-1.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="5678" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install runtime dependencies
RUN pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy n8n from builder and fix permissions for non-root execution
COPY --from=builder /app/version /app/version
COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules

RUN ln -sf /usr/local/lib/node_modules/n8n/bin/n8n /usr/local/bin/n8n && \
    ln -sf /usr/local/bin/python3.13 /usr/local/bin/python3 && \
    ln -sf /usr/local/bin/python3.13 /usr/local/bin/python && \
    rm -f /usr/local/lib/node_modules/@n8n/task-runner-python/.venv/bin/python3 && \
    ln -s /usr/local/bin/python3.13 /usr/local/lib/node_modules/@n8n/task-runner-python/.venv/bin/python3 && \
    chmod -R o+rX /usr/local/lib/node_modules && \
    find /usr/local/lib/node_modules/n8n -type d -name "sqlite" -path "*/migrations/*" | \
      xargs -I{} find {} -name "*.js" | \
      xargs perl -pi -e \
        's{((?:WHERE|SET|AND|OR)\b[^=]+=\s*)"([^"]+)"}{$1'"'"'$2'"'"'}gi; s{(\bIN\s*\(\s*)"([^"]+)"}{$1'"'"'$2'"'"'}gi; s{\bVALUES\s*\(([^)]*)\)}{my $v=$1; $v=~s{"([^"]+)"}{'"'"'$1'"'"'}g; "VALUES ($v)"}gie'

COPY patches/patch-sqlite.js /tmp/patch-sqlite.js
RUN node /tmp/patch-sqlite.js && rm /tmp/patch-sqlite.js

# Create config directory
RUN mkdir -p /config && \
    chown -R bsd:bsd /config

# Copy service definitions and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# Environment
ENV N8N_USER_FOLDER=/config \
    N8N_PORT=5678 \
    N8N_PROTOCOL=http \
    N8N_LISTEN_ADDRESS=0.0.0.0 \
    NODE_ENV=production

# --- Expose (Injected by Generator) ---
EXPOSE 5678

# --- Volumes (Injected by Generator) ---
VOLUME /config